# This is a basic workflow to help you get started with Actions

name: "UBI: buildbot-master"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: 
       - 'buildbot-master/**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-buildbo-master-ubi-image:
    uses: ./.github/workflows/ubi_base_workflow.yml
    with:
      app: buildbot-master
      registry: ${{ secrets.REGISTRY_SERVER }}
      registry_namespace: ${{ secrets.REGISTRY_NAMESPACE }}
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}