name: UBI base workflow

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      registry:
        required: true
        type: string
        
jobs:
 
  build-scan-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - name: Enable docker experimental feature
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the ${{ inputs.app }} UBI image
        run:  DOCKER_CLI_EXPERIMENTAL=enabled docker build --squash ./${{ inputs.app }}/ --file ./${{ inputs.app }}/Dockerfile.${{ inputs.app }} --tag ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.app }}:${{ github.run_id }} --tag ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.app }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@cb606dfdb0d2b3698ace62192088ef4f5360b24f #v0.6.2
        with:
          image-ref: "${{ inputs.registry }}/${{ github.repository }}/${{ inputs.app }}:${{ github.run_id }}"
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@bbc2e7010f187d73e9eb71ea708c31bbbe580964 #v2.1.18
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push the image
        run: docker push --all-tags ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.app }}
