name: UBI base workflow

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        
jobs:
 
  build-scan-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - name: Enable docker experimental feature
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build the ${{ inputs.app }} UBI image
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker build \
          --squash ./${{ inputs.app }}/ \
          --file ./${{ inputs.app }}/Dockerfile.${{ inputs.app }} \
          --tag ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ inputs.app }}:${{ github.run_id }} \
          --tag ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ inputs.app }}:latest

      - name: Push the image
        run: docker push --all-tags ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ inputs.app }}
